name: Linting

on: pull_request

jobs:
<<<<<<< HEAD
  prettier-check:
=======
  prettier:
>>>>>>> 16003e2fe06f3f76035251c7c2a87a7349cbfd33
    name: Prittier
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
    
      - run: npm ci

<<<<<<< HEAD
      - run: npm run lint:prittier:check

    prettier-fix:
    name: Prittier
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
    
      - run: npm ci

    - run: npm run lint:prittier:fix
=======
      - run: npm run lint:prittier:check
>>>>>>> 16003e2fe06f3f76035251c7c2a87a7349cbfd33
